//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApproximationClient.ServiceApproximation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceApproximation.IServiceApproximation")]
    public interface IServiceApproximation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApproximation/Approximate", ReplyAction="http://tempuri.org/IServiceApproximation/ApproximateResponse")]
        System.ValueTuple<double[], double[]> Approximate(double[] xValues, double[] yValues);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceApproximation/Approximate", ReplyAction="http://tempuri.org/IServiceApproximation/ApproximateResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<double[], double[]>> ApproximateAsync(double[] xValues, double[] yValues);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceApproximationChannel : ApproximationClient.ServiceApproximation.IServiceApproximation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceApproximationClient : System.ServiceModel.ClientBase<ApproximationClient.ServiceApproximation.IServiceApproximation>, ApproximationClient.ServiceApproximation.IServiceApproximation {
        
        public ServiceApproximationClient() {
        }
        
        public ServiceApproximationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceApproximationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceApproximationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceApproximationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ValueTuple<double[], double[]> Approximate(double[] xValues, double[] yValues) {
            return base.Channel.Approximate(xValues, yValues);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<double[], double[]>> ApproximateAsync(double[] xValues, double[] yValues) {
            return base.Channel.ApproximateAsync(xValues, yValues);
        }
    }
}
